# Gemini CLI custom slash command for code review (develop/local)

# 事前にdevelopブランチもローカルで最新化しておく必要が有る

description = "ローカルの現在のブランチとdevelopの差分に対してコードレビューを行う。"

prompt = """
ローカルの現在のブランチとdevelopブランチの差分に対してコードレビューを行ってください。
以下のファイルに記載のコードレビュー観点を中心にレビューしてください。
/Users/yuki_yoshida/Projects/Buyer/rtb/GEMINI.md
"""
