# 事前にdevelopブランチもローカルで最新化しておく必要が有る

description = "ローカルの現在のブランチとdevelopのコミット済みの差分に対して手動結合テストケースの作成を行う。"

prompt = """
ローカルの現在のブランチとdevelopブランチのコミット済みの差分に対して手動結合テストケースの作成を行ってください。
単体テストでカバー済みの範囲も確認しつつ、手動結合テストとしてふさわしい内容にしてください。
"""
